### PR TITLE
Adding Docker image and update documentation

### PR DESCRIPTION
**Pull request by mguyard**

### CODE REVIEW

**Comment by mguyard** [comment]
I've also add in last commit, modbus script provided and create a container for this.
I've updated code to quickly deploy. All works but please review it.

**Review by br1pro — APPROVED** [review]
I tested the Dockerfile and it works

**Review by br1pro — COMMENTED** [review]
Ok for the dockerfile integration.
Instead the "docker run --rm -p 1880:1880 -p 502:502 --name vsPLC mguyard/vsplc:latest" doesn't work in my linux environment docker says the container image you have created is for arm cpus. I believe is better to use the docker build from github directly

**Comment by mguyard** [comment]
Yes. My bad. Only generate arm64 build. Now it's better
CleanShot 2023-12-04 at 16 19 17@2x

Can you try if now it's work with command defined in README ?

**Comment by br1pro** [comment]
I like your work, you are free to put it your repository. 
I' d like to leave here open the way how to send ModbusTCP commands to vsPLC.

**Pull request closed without merging**
